import type {
  Anomaly,
  ReconciliationRecord,
  Transaction,
  UploadSource,
} from "@/lib/types";

export const periodSummaries = {
  "This Month": {
    revenue: 248_420,
    revenueTrend: 12.8,
    expenses: 181_230,
    expenseTrend: 4.1,
    cashFlow: 67_190,
    cashFlowTrend: 18.2,
    reconciliation: 96.8,
    reconciliationTrend: 2.1,
    comparison: "vs. Jul 2026",
  },
  "Last Month": {
    revenue: 220_250,
    revenueTrend: 4.6,
    expenses: 174_880,
    expenseTrend: 2.8,
    cashFlow: 45_370,
    cashFlowTrend: 6.4,
    reconciliation: 94.8,
    reconciliationTrend: 0.9,
    comparison: "vs. Jun 2026",
  },
  Quarter: {
    revenue: 691_670,
    revenueTrend: 9.7,
    expenses: 507_910,
    expenseTrend: 3.9,
    cashFlow: 183_760,
    cashFlowTrend: 14.5,
    reconciliation: 96.1,
    reconciliationTrend: 1.7,
    comparison: "vs. prior quarter",
  },
  Year: {
    revenue: 2_478_820,
    revenueTrend: 11.2,
    expenses: 1_771_450,
    expenseTrend: 5.3,
    cashFlow: 707_370,
    cashFlowTrend: 17.9,
    reconciliation: 95.4,
    reconciliationTrend: 1.4,
    comparison: "vs. prior year",
  },
} as const;

export type PeriodLabel = keyof typeof periodSummaries;

export const monthlyFinancials = [
  { month: "Sep '25", revenue: 169_200, expenses: 124_600 },
  { month: "Oct '25", revenue: 185_400, expenses: 135_900 },
  { month: "Nov '25", revenue: 189_700, expenses: 137_100 },
  { month: "Dec '25", revenue: 233_900, expenses: 160_700 },
  { month: "Jan '26", revenue: 202_100, expenses: 149_100 },
  { month: "Feb '26", revenue: 196_800, expenses: 139_800 },
  { month: "Mar '26", revenue: 199_500, expenses: 150_400 },
  { month: "Apr '26", revenue: 215_300, expenses: 158_300 },
  { month: "May '26", revenue: 212_600, expenses: 155_900 },
  { month: "Jun '26", revenue: 222_950, expenses: 151_800 },
  { month: "Jul '26", revenue: 220_250, expenses: 174_880 },
  { month: "Aug '26", revenue: 248_420, expenses: 181_230 },
];

export const cashFlowForecast = [
  { month: "Mar", value: 49_100, type: "Historical" },
  { month: "Apr", value: 57_000, type: "Historical" },
  { month: "May", value: 56_700, type: "Historical" },
  { month: "Jun", value: 71_150, type: "Historical" },
  { month: "Jul", value: 45_370, type: "Historical" },
  { month: "Aug", value: 67_190, type: "Historical" },
  { month: "Sep", value: 72_300, type: "Forecast" },
  { month: "Oct", value: 76_100, type: "Forecast" },
  { month: "Nov", value: 81_400, type: "Forecast" },
] as const;

export const expenseBreakdown = [
  { label: "Payroll", value: 42, color: "#0e7c74" },
  { label: "Operations", value: 19, color: "#3d63dd" },
  { label: "Marketing", value: 14, color: "#7c67c7" },
  { label: "Utilities", value: 9, color: "#f39c2d" },
  { label: "Transport", value: 7, color: "#d98700" },
  { label: "Others", value: 9, color: "#98a2b3" },
];

export const budgetVariances = [
  { category: "Marketing", budget: 20_000, actual: 25_600, variance: 28 },
  { category: "Transport", budget: 12_000, actual: 14_100, variance: 17.5 },
  { category: "Payroll", budget: 78_000, actual: 76_500, variance: -1.9 },
  { category: "Operations", budget: 38_000, actual: 36_950, variance: -2.8 },
  { category: "Utilities", budget: 16_500, actual: 16_380, variance: -0.7 },
];

export const transactions: Transaction[] = [
  {
    id: "TXN-2849",
    date: "28 Aug 2026",
    description: "ABC Enterprise",
    reference: "INV-8821",
    category: "Operations",
    account: "Operating Account",
    amount: -18_940,
    source: "Bank",
    status: "Anomaly",
    note: "Amount is 520% above the supplier's historical payment range.",
  },
  {
    id: "TXN-2848",
    date: "27 Aug 2026",
    description: "Customer Payment",
    reference: "INV-7753",
    category: "Revenue",
    account: "Operating Account",
    amount: 24_500,
    source: "Ledger",
    status: "Matched",
    note: "Matched to bank receipt BR-2088 with exact amount and reference.",
  },
  {
    id: "TXN-2847",
    date: "26 Aug 2026",
    description: "META ADS",
    reference: "MKT-3821",
    category: "Marketing",
    account: "Corporate Card",
    amount: -7_230,
    source: "Bank",
    status: "Review",
    note: "Monthly digital advertising spend is above its normal range.",
  },
  {
    id: "TXN-2846",
    date: "25 Aug 2026",
    description: "Payroll Disbursement",
    reference: "PAY-AUG-26",
    category: "Payroll",
    account: "Payroll Account",
    amount: -76_500,
    source: "Ledger",
    status: "Matched",
    note: "Matched to the consolidated payroll bank debit.",
  },
  {
    id: "TXN-2845",
    date: "24 Aug 2026",
    description: "Sarawak Energy",
    reference: "SEB-49802",
    category: "Utilities",
    account: "Operating Account",
    amount: -16_380,
    source: "Bank",
    status: "Suggested",
    note: "Suggested against ledger item UTL-AUG with 88% confidence.",
  },
  {
    id: "TXN-2844",
    date: "23 Aug 2026",
    description: "Client Retainer",
    reference: "RET-2026-08",
    category: "Revenue",
    account: "Operating Account",
    amount: 38_500,
    source: "Bank",
    status: "Matched",
    note: "Matched to management ledger receipt on the same date.",
  },
  {
    id: "TXN-2843",
    date: "22 Aug 2026",
    description: "Swift Logistics",
    reference: "SL-7742",
    category: "Transport",
    account: "Operating Account",
    amount: -14_100,
    source: "Ledger",
    status: "Unmatched",
    note: "No bank record within the configured five-day matching window.",
  },
  {
    id: "TXN-2842",
    date: "21 Aug 2026",
    description: "Office Mart",
    reference: "OM-1139",
    category: "Operations",
    account: "Corporate Card",
    amount: -11_500,
    source: "Bank",
    status: "Anomaly",
    note: "Possible duplicate of the 19 Aug office supplies payment.",
  },
  {
    id: "TXN-2841",
    date: "20 Aug 2026",
    description: "Software License",
    reference: "SFT-9201",
    category: "Operations",
    account: "Corporate Card",
    amount: -6_420,
    source: "Ledger",
    status: "Review",
    note: "Reference format differs from the corresponding bank memo.",
  },
  {
    id: "TXN-2840",
    date: "19 Aug 2026",
    description: "ABC Supplier Sdn Bhd",
    reference: "INV-928",
    category: "Operations",
    account: "Operating Account",
    amount: -4_500,
    source: "Ledger",
    status: "Suggested",
    note: "Suggested match to ABC SUPPLIER / 928 with 96% confidence.",
  },
  {
    id: "TXN-2839",
    date: "18 Aug 2026",
    description: "Travel Reimbursement",
    reference: "TRV-0818",
    category: "Transport",
    account: "Petty Cash",
    amount: -1_860,
    source: "Ledger",
    status: "Suggested",
    note: "Suggested against a same-day bank transfer with 81% confidence.",
  },
  {
    id: "TXN-2838",
    date: "17 Aug 2026",
    description: "Regional Service Income",
    reference: "RSI-0448",
    category: "Revenue",
    account: "Operating Account",
    amount: 18_760,
    source: "Bank",
    status: "Matched",
    note: "Matched to ledger receipt RSI-0448.",
  },
];

export const reconciliationRecords: ReconciliationRecord[] = [
  {
    id: "REC-928",
    confidence: 96,
    classification: "Automatic Match",
    ledger: {
      date: "15 Aug 2026",
      description: "ABC SUPPLIER SDN BHD",
      reference: "INV-928",
      amount: 4_500,
    },
    bank: {
      date: "16 Aug 2026",
      description: "ABC SUPPLIER",
      reference: "928",
      amount: 4_500,
    },
    factors: { amount: 100, date: 92, description: 94, reference: 98 },
    explanation:
      "Strong amount, reference and description alignment. One-day posting difference detected.",
    resolution: "Pending",
  },
  {
    id: "REC-7742",
    confidence: 84,
    classification: "Suggested Match",
    ledger: {
      date: "14 Aug 2026",
      description: "GLOBAL LOGISTICS SDN BHD",
      reference: "GL-7742",
      amount: 2_120,
    },
    bank: {
      date: "15 Aug 2026",
      description: "GLOBAL LOGISTICS",
      reference: "7742",
      amount: 2_120,
    },
    factors: { amount: 100, date: 88, description: 82, reference: 74 },
    explanation:
      "Amount and vendor align, but the abbreviated reference requires confirmation.",
    resolution: "Pending",
  },
  {
    id: "REC-3311",
    confidence: 72,
    classification: "Manual Review",
    ledger: {
      date: "12 Aug 2026",
      description: "OFFICE DEPOT",
      reference: "OD-3311",
      amount: 785.4,
    },
    bank: {
      date: "13 Aug 2026",
      description: "OFFICE DPT KCH",
      reference: "-",
      amount: 789.4,
    },
    factors: { amount: 78, date: 86, description: 76, reference: 42 },
    explanation:
      "Vendor and date are plausible; amount differs by RM 4.00 and no bank reference is available.",
    resolution: "Pending",
  },
];

export const anomalies: Anomaly[] = [
  {
    id: "ANM-001",
    date: "28 Aug 2026",
    transaction: "ABC Enterprise",
    category: "Operations",
    amount: 18_940,
    score: 0.93,
    risk: "High",
    status: "Open",
    reasons: [
      "520% higher than typical supplier payment",
      "Vendor has only appeared once previously",
      "Category expenditure exceeds monthly average",
    ],
    historicalAverage: 3_640,
  },
  {
    id: "ANM-002",
    date: "21 Aug 2026",
    transaction: "Duplicate Payment Suspected",
    category: "Operations",
    amount: 11_500,
    score: 0.91,
    risk: "High",
    status: "Investigating",
    reasons: [
      "Same vendor and amount appeared within 48 hours",
      "Reference differs by one character",
      "No corresponding purchase order found",
    ],
    historicalAverage: 2_780,
  },
  {
    id: "ANM-003",
    date: "30 Aug 2026",
    transaction: "Weekend Bank Transfer",
    category: "Operations",
    amount: 9_800,
    score: 0.88,
    risk: "High",
    status: "Open",
    reasons: [
      "Transaction occurred outside the normal operating window",
      "New beneficiary account",
      "Amount is above weekend transaction threshold",
    ],
    historicalAverage: 1_950,
  },
  {
    id: "ANM-004",
    date: "26 Aug 2026",
    transaction: "META ADS",
    category: "Marketing",
    amount: 7_230,
    score: 0.82,
    risk: "Medium",
    status: "Reviewed",
    reasons: [
      "Digital advertising spend rose 21.3% above budget",
      "Three charges posted within one week",
    ],
    historicalAverage: 4_820,
  },
  {
    id: "ANM-005",
    date: "24 Aug 2026",
    transaction: "Utility Consumption Spike",
    category: "Utilities",
    amount: 16_380,
    score: 0.78,
    risk: "Medium",
    status: "Open",
    reasons: [
      "Usage-related charges are 34% above the rolling average",
      "Seasonal pattern does not explain the increase",
    ],
    historicalAverage: 12_220,
  },
  {
    id: "ANM-006",
    date: "18 Aug 2026",
    transaction: "Travel Reimbursement Pattern",
    category: "Transport",
    amount: 5_640,
    score: 0.76,
    risk: "Medium",
    status: "Dismissed",
    reasons: [
      "Three reimbursements share similar descriptions",
      "Monthly transport spend is above forecast",
    ],
    historicalAverage: 2_410,
  },
  {
    id: "ANM-007",
    date: "11 Aug 2026",
    transaction: "KCH Business Supply",
    category: "Operations",
    amount: 6_950,
    score: 0.73,
    risk: "Medium",
    status: "Reviewed",
    reasons: [
      "Vendor is new to this account",
      "Amount is 82% above the category median",
    ],
    historicalAverage: 3_820,
  },
];

export const uploadedSources: Array<{
  source: UploadSource;
  filename: string;
  fileType: string;
  records: number;
  uploaded: string;
}> = [
  {
    source: "Ledger",
    filename: "general-ledger-aug-2026.xlsx",
    fileType: "XLSX",
    records: 1_240,
    uploaded: "1 Sep 2026 · 09:12",
  },
  {
    source: "Bank Statement",
    filename: "bank-statement-aug-2026.csv",
    fileType: "CSV",
    records: 662,
    uploaded: "1 Sep 2026 · 09:16",
  },
  {
    source: "Budget",
    filename: "budget-2026.xlsx",
    fileType: "XLSX",
    records: 84,
    uploaded: "31 Aug 2026 · 17:44",
  },
];

export const successMetrics = [
  {
    label: "Reconciliation accuracy",
    value: "96.8%",
    target: "Target ≥95%",
  },
  {
    label: "Report generation reduction",
    value: "81%",
    target: "Target ≥60%",
  },
  {
    label: "Forecast variance",
    value: "7.6%",
    target: "Target ≤10%",
  },
  {
    label: "Anomaly precision",
    value: "89%",
    target: "Target ≥85%",
  },
];

export const financialInsights = [
  "Marketing expenditure increased 21.3% above budget this month.",
  "Revenue grew 12.8%, while expenses increased only 4.1%.",
  "Operating cash flow improved for the third consecutive month.",
  "Transport expenditure is trending 17.5% above forecast.",
];

export const reportSections = [
  "Executive Summary",
  "Financial Performance",
  "Revenue Analysis",
  "Expense Analysis",
  "Budget Variance",
  "Cash Flow Forecast",
  "Anomalies",
  "Reconciliation Summary",
];
